name: CICD

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
  

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with: 
        name: war-package
        path: ./build/libs/*.war
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: war-package
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.10.0
      with:
        context: ./
        file: ./Dockerfile/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/m-dev:tomcat_latest
